const FETCH_PRACTICE_PENDING = 'FETCH_PRACTICE_PENDING';
const FETCH_PRACTICE_SUCCESS = 'FETCH_PRACTICE_SUCCESS';
const FETCH_PRACTICE_ERROR = 'FETCH_PRACTICE_ERROR';

export { FETCH_PRACTICE_PENDING, FETCH_PRACTICE_SUCCESS, FETCH_PRACTICE_ERROR };
