const FETCH_REQUEST_PENDING = 'FETCH_REQUEST_PENDING';
const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';
const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';

export { FETCH_REQUEST_PENDING, FETCH_REQUEST_SUCCESS, FETCH_REQUEST_ERROR };
