const FETCH_PRACTICES_PENDING = 'FETCH_PRACTICES_PENDING';
const FETCH_PRACTICES_SUCCESS = 'FETCH_PRACTICES_SUCCESS';
const FETCH_PRACTICES_ERROR = 'FETCH_PRACTICES_ERROR';

export { FETCH_PRACTICES_PENDING, FETCH_PRACTICES_SUCCESS, FETCH_PRACTICES_ERROR };
