const GET_PRACTICE_PENDING = 'GET_PRACTICE_PENDING';
const GET_PRACTICE_SUCCESS = 'GET_PRACTICE_SUCCESS';
const GET_PRACTICE_ERROR = 'GET_PRACTICE_ERROR';

export { GET_PRACTICE_PENDING, GET_PRACTICE_SUCCESS, GET_PRACTICE_ERROR };
